extends: airbnb/base # TODO: add es6 compiler and move away from legacy.
parser: babel-eslint
plugins:
  - mocha
  - flowtype
rules:
  mocha/no-exclusive-tests: 2

  prefer-template: 0
  prefer-arrow-callback: 0
  func-names: 0
  no-else-return: 0
  vars-on-top: 0
  max-len: 0
  wrap-iife: 0
  new-cap: 0
  consistent-return: 0

  prefer-const: 0

  guard-for-in: 0
  block-scoped-var: 0
  no-redeclare: 0
  comma-dangle: 0
  no-shadow: 0
  no-param-reassign: 0
