extends: airbnb/base
parser: babel-eslint
plugins:
  - mocha
  - flowtype
rules:
  mocha/no-exclusive-tests: 2
  flowtype/require-valid-file-annotation: 2

  prefer-template: 0
  no-else-return: 0
  max-len: 0
  new-cap: 0
  consistent-return: 0
  prefer-const: 0
  comma-dangle: 0
  no-param-reassign: 0

  no-underscore-dangle: 0
  arrow-body-style: 0
