extends: airbnb/base # TODO: add es6 compiler and move away from legacy.
plugins:
  - mocha
  - flowtype
rules:
  mocha/no-exclusive-tests: 2

  prefer-const: 0
  no-var: 0
  object-shorthand: 0
  prefer-template: 0
  prefer-arrow-callback: 0
  camelcase: 0

  func-names: 0
  comma-dangle: 0
  no-param-reassign: 0
  no-else-return: 0
  vars-on-top: 0
  max-len: 0
  wrap-iife: 0
  new-cap: 0
  no-shadow: 0
  consistent-return: 0
  no-nested-ternary: 0
  dot-notation: 0
