name: javascript
version: 4.2.4
schema: 1
scm: github.com/pubnub/javascript
changelog:
  - version: v4.2.4
    date:
    changes:
      - type: improvement
        text: detection of support of promises improved.
  - version: v4.2.3
    date:
    changes:
      - type: improvement
        text: fixes on encoding of apostraphes.
  - version: v4.2.2
    date:
    changes:
      - type: improvement
        text: add promise support on setState operation (@jskrzypek)
      - type: improvement
        text: add hooks to stop polling time when the number of subscriptions drops to 0 (@jasonpoe)
  - version: v4.2.1
    date:
    changes:
      - type: improvement
        text: encode signatures to avoid sending restricted characters
  - version: v4.2.0
    date:
    changes:
      - type: improvement
        text: Add optional support for promises on all endpoints.
      - type: improvement
        text: History always returns timetokens in the payloads.
      - type: improvement
        text: Optionally, if queue size is set, send status on queue size threshold
  - version: v4.1.1
    date:
    changes:
      - type: improvement
        text: fix state setting for channels with reserved tags.
  - version: v4.1.0
    date:
    changes:
      - type: improvement
        text: reset timetoken when all unsubscribes happen
      - type: improvement
        text: sign requests when a a secret key is passed
  - version: v4.0.13
    date:
    changes:
      - type: improvement
        text: propogate status events to the status callback on subscribe operations.
  - version: v4.0.12
    date:
    changes:
      - type: improvement
        text: affectedChannels and affectedChannelGroups are now populated on subscribe / unsubscribe events
  - version: v4.0.11
    date:
    changes:
      - type: improvement
        text: dependency upgrades
  - version: v4.0.10
    date:
    changes:
      - type: improvement
        text: expose decryption and encryption as a global
  - version: v4.0.9
    date:
    changes:
      - type: improvement
        text: channel / subscription items are populated in
      - type: improvement
        text: constants for operation and category are exposed on global object
  - version: v4.0.8
    date:
    changes:
      - type: improvement
        text: re-publish of v4.0.7
  - version: v4.0.7
    date:
    changes:
      - type: improvement
        text: Dependency upgrades
      - type: improvement
        text: try..catch wrapped around localStorage for iframe compliance
  - version: v4.0.6
    date:
    changes:
      - type: improvement
        text: Adjustment of reconnection policies for web distributions.
      - type: improvement
        text: PNSDK support for partner identification
  - version: v4.0.5
    date:
    changes:
      - type: improvement
        text: Stop exposing .babelrc which causes unpredictable behavior on react native.
  - version: v4.0.4
    changes:
      - type: improvement
        text: Adjust handling of presence payloads for state settings.
      - type: feature
        text: Exposing generateUUID method to create uuids.
      - type: improvement
        text: Triggering disconnect, reconnect events on Web distributions.
      - type: improvement
        text: React Native adjustments to package.json information.
  - version: v4.0.3
    changes:
      - type: improvement
        text: Global Here Now parsing adjustments.
  - version: v4.0.2
    changes:
      - type: improvement
        text: Adjustments to internet disconnects on node.
  - version: v4.0.1
    changes:
      - type: bug
        text: Fixes to avoid double encoding on JSON payloads.
  - version: v4.0.0
    changes:
      - type: feature
        text:  New iteration of JS / Node SDK family
features:
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  access:
    - ACCESS-GRANT
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
    - PUBLISH-ASYNC
    - PUBLISH-FIRE
    - PUBLISH-REPLICATION-FLAG
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
