language: node_js
sudo: false
node_js:
  - '0.08'
  - '0.10'
  - '0.12'
  - 'iojs'
  - '4'
  - '6'

before_install:
  npm install --global gulp-cli

install:
  npm install

script:
  gulp test

after_success:
  - npm install codecov
  - npm run codecov
