language: node_js
sudo: false
node_js:
  - '4'
  - '5'
  - '6'

before_install:
  npm install --global yarn
  npm install --global gulp-cli

install:
  yarn install

script:
  gulp test

after_success:
  - npm install codecov
  - npm run codecov
