language: node_js
sudo: false
node_js:
  - '8.10.0'
  - '10.13.0'
  - '12'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - gulp test
after_success:
  - npm install codecov codacy-coverage
  - cat ./coverage/lcov.info | node_modules/.bin/codacy-coverage
