name: Commands processor

on:
  issue_comment:
    types: [created]

jobs:
  process:
    name: Process command
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '@client-engineering-bot ') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout release actions
        uses: actions/checkout@v2
        with:
          repository: pubnub/client-engineering-deployment-tools
          ref: github-actions
          token: ${{ secrets.GH_TOKEN }}
          path: ".github/.release/actions"
      - name: Run changelogs actions
        uses: "./.github/.release/actions/actions/commands"
        with:
          token: ${{ secrets.GH_TOKEN }}
          listener: client-engineering-bot
          publisher-name: Serhii Mamontov
          publisher-email: parfeon@me.com
